### ISSUE TITLE
Add ISO Excellence Award somewhere obvious

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#1]
As attached.

![iso-tc-211](https://user-images.githubusercontent.com/11865/51133369-cb22c200-186f-11e9-8ea9-2c80eaab46d2.jpg)

**Comment by ronaldtse** [comment]
@strogonoff you probably know a good place for this. 

This should be a separate page. 

The official ISO news article is here: https://www.iso.org/news/2010/09/Ref1354.html

**Comment by ronaldtse** [comment]
@strogonoff ping 😉

**Comment by strogonoff** [comment]
I think a separate page (blog post in this case, linked from landing) makes best sense after all, should be live today/tomorrow.

**Comment by ronaldtse** [comment]
Thanks @strogonoff ! Can we also place the wording "Winner of the Lawrence D. Eicher Leadership Award" somewhere, e.g. footer, header (and link it to the page)?

**Comment by strogonoff** [comment]
The award post is live. It shows the picture of the award and links to ISO press release for more details. Added news entry illustration support feature to jekyll-theme-isotc211.

**Comment by strogonoff** [comment]
@ronaldtse we can show it in the footer, excluding landing page to try to reduce perceived vanity ;)

**Comment by ronaldtse** [comment]
> we can show it in the footer, excluding landing page to try to reduce perceived vanity ;)

Vanity in this case is better being consistent. Let's put it in the footer :-)

**Comment by strogonoff** [comment]
The next logical question would be “why be consistent in this particular matter?” In any case, I’m fine with implementing this design choice as given.

**Comment by ronaldtse** [comment]
Oh, the less conditionals we have the easier to manage.

**Comment by ronaldtse** [comment]
Thanks @strogonoff !

**Comment by strogonoff** [comment]
The conditionals is not an obstacle for good UX 💪

By the way, I believe “the” is not necessary. We’re listing awards this TC has won and this award just happens to be it, and “the” is not part of award name. I have omitted the definite article on purpose

**Comment by strogonoff** [comment]
The award banner isn’t finished yet, I want to keep it open until next release

**Comment by ronaldtse** [comment]
@strogonoff are you talking about this "The" in the footer? I think it's appropriate as now. In fact that's what the certificate exactly says.

Sure, keep it open.

<img width="360" alt="Screen Shot 2019-03-25 at 10 41 02 PM" src="https://user-images.githubusercontent.com/11865/54928579-1253c000-4f4f-11e9-898f-a678006a90c2.png">

**Comment by strogonoff** [comment]
* The phrasing on the certificate includes the definite article, but the article is not part of award name from my prior research.
* You can see the award referred to in different ways in these materials (with the article, without it, shortened to “LDE award”, and so on). The article is typically formatted outside of award title and is not capitalized.
  * [Entry on the _ISO awards_ page](https://www.iso.org/iso-awards.html#lde-anchor)
  * [LDE Award brochure](https://www.iso.org/files/live/sites/isoorg/files/store/en/PUB100381.pdf)
  * [2015 LDE Award press release](https://www.din.de/en/din-and-our-partners/press/press-releases/lawrence-d-eicher-leadership-award-2015--79926)
* On TC 211 site, when prepended with the year (like it is now), “the” doesn’t sound wrong to me. However, I took care of not capitalizing it.
* If multiple awards are configured, the phrasing _will_ sound clumsy, but we can deal with it later if this happens.

**Comment by ronaldtse** [comment]
@strogonoff agree, the article isn't part of the award. Please help update when you have time. Thanks.

**Comment by ronaldtse** [comment]
And close this once it's done. Thanks.

**Comment by strogonoff** [comment]
It’s not done yet

**Comment by ronaldtse** [comment]
Seems like it's done. Thanks!
