### ISSUE TITLE
Namespace URL report

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#15]
We've just received this report regarding namespaces. See below.

> Dear colleges.
>
> The namespaces urls are giving us error, we use them at the beginning of our metadata. Have you change the urls? Is it something temporal?
>
> xmlns:gco="http://www.isotc211.org/2005/gco" 
> xmlns:gmd="http://www.isotc211.org/2005/gmd" 
> xmlns:gmx="http://www.isotc211.org/2005/gmx" ...
>Thank you.
>
>Regards. Margarita

The issue is that these are namespace URIs, not actual HTTP URLs. For example, the file for `http://www.isotc211.org/2005/gmd` is at `https://www.isotc211.org/2005/gmd/gmd.xsd`. 

This also relates to #5 .

Any thoughts? @jetgeo @tedhabermann @PeterParslow

**Comment by smrgeoinfo** [comment]
Yes, that is the answer. Those strings ("http://ww.isotc211.org/2005/gco") are identifiers (http URI's technically). They do not necessarily resolve to a useful representation although it has become common practice to set them up so they do resolve to something.  They could equally well be UUID's or URNs. The schemaLocation property binds the identifier to a web location (URL) where the xml schema can be gotten.

**Comment by ronaldtse** [comment]
Thanks @smrgeoinfo , let me contact Margarita and let her know that this is the official response. 

However, while technically this is not supposed to be an issue, but there have already been two questions on this. I think this means that there are implementations that depend on the resolvability of these links (confusing with `schemaLocation`).

What's your take?

**Comment by ronaldtse** [comment]
(I'd like to add that this user is from the Generalitat Valenciana, http://www.gva.es/)

**Comment by smrgeoinfo** [comment]
I would assert that an application that depends on resolvability of a namespace URI is not consistent with the xml specifications, and does not need to be supported by 3rd parties (e.g. ISO). I'd be interested to hear if there are other opinions on the subject.

**Comment by dr-shorthair** [comment]
Steve – you are correct that the XML specs do not require that a namespace formulated to look like a HTTP URI be resolvable.
But expectations of developers should also be taken into account – if it looks like a URL, but doesn’t resolve, then they may assume something is broken and go elsewhere …

Simon

**Comment by PeterParslow** [comment]
It is a sad fact of life that "developers"* will use technologies (such as XML) with very limited understanding, and move on quickly if they don't get quick results :)

I was tempted to say "developers of today" :)

**Comment by ronaldtse** [comment]
Following up on this issue, can we create an "FAQ" page so people can find answers without asking us?

**Comment by jetgeo** [comment]
Agree, a FAQ page is good to have for a number of reasons.

**Comment by ronaldtse** [comment]
Added FAQ question in 9058117 now.
