### ISSUE TITLE
Add agreements with external parties

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#2]
OGC and DGIWG.

[Agreement_DGIWG.pdf](https://github.com/ISO-TC211/www.isotc211.org/files/2756633/Agreement_DGIWG.pdf)
[Agreement_OGC.pdf](https://github.com/ISO-TC211/www.isotc211.org/files/2756634/Agreement_OGC.pdf)

**Comment by ronaldtse** [comment]
@strogonoff can you add a page for this?

**Comment by strogonoff** [comment]
on it

**Comment by strogonoff** [comment]
@ronaldtse Whoops, this slipped through the cracks…

Should agreements with external parties go on www.isotc211.org only, or on resource sub-sites as well?

**Comment by strogonoff** [comment]
@ronaldtse Another question:

Are these agreements a feature to be stressed, or a legal moment similar to ToS/privacy policy? This will affect how prominently and where the link will be displayed.

**Comment by strogonoff** [comment]
By the way, the DGIWG document uses the former abbreviation for DGIWG (it’s currently named https://en.wikipedia.org/wiki/Defence_Geospatial_Information_Working_Group), I suppose everyone is aware but perhaps there’s a newer document somewhere.

**Comment by ronaldtse** [comment]
@strogonoff I think these agreements should only be on the www site, maybe either a post (as news) or as a separate category to show which partners work with TC 211. We should definitely clarify the abbreviations.

**Comment by strogonoff** [comment]
I meant inside PDF itself the abbreviation explanation is wrong. He entity changed name.

I will update the one on the site of course.

**Comment by ronaldtse** [comment]
Ah, got it. Thanks!

**Comment by jetgeo** [comment]
I think you need to clarify with Mats about this issue. This is clearly information for the main ISO/TC 211 page. I see it’s relevance for the resources page as well, but at least OGC has its own schema repository.

**Comment by ronaldtse** [comment]
@jetgeo thanks for the advice. Either way is fine with us. Our motivation is to ensure everything from the old site is again placed online. 

@matsahlin what do you think? If these are added to the committee site we won’t duplicate them here. Thanks!

**Comment by MatsAhlin** [comment]
These document should not be on the http://www.isotc211.org site. They are kept on Livelink by ISO.
The should not be public accessible according to ISO central secretary, so please leave these out of the published parts.

Thank you.

**Comment by ronaldtse** [comment]
@MatsAhlin I see, these documents were provided to the public in the old www.isotc211.org site. But since these shouldn't be accessible, let's close this.
