### ISSUE TITLE
Geolexica is a resource site too?

### ISSUE THREAD

**Issue by strogonoff** [ISO-TC211/www.isotc211.org#20]
Currently, our ISO TC 211 resource site links to standard models & schemas; how does Geolexica fit there? It seems logical to include it in resource index to make navigation across TC 211 resources complete.

I’m not requesting a PR, just clarifying conceptually. (If Geolexica belongs here, please don’t go ahead and add it just yet, the 3-column landing layout might not accommodate it gracefully and then I’ll have to clean it up instead of doing the right way from the beginning)

**Comment by ronaldtse** [comment]
@strogonoff I guess we can consider Geolexica a "resource site". For sure though we want to add a link from www.isotc211.org. I completely forgot about linking.

**Comment by ronaldtse** [comment]
BTW the HTML in the `index.adoc` is quite horrifying 😉 It would be great if we can clean that up.

**Comment by strogonoff** [comment]
@ronaldtse Sorry if unclosed HTML tags triggered you ;) I believe at this stage lower maintenance overhead is worth it (as long as markup conforms to the spec and thus is interpreted consistently across browsers). Once landing markup stabilizes, maybe moves to HTML layout etc., I’ll be open to be more explicit

Also yeah, this should be an HTML file at this point, AsciiDoc markup doesn’t provide enough flexibility (I had to dig through many open issues on their GitHub).

Anyway this is fluid right now so please resist the temptation to jump in and correct everything, I’ll waste 2x time merging >__<

**Comment by strogonoff** [comment]
Created #22 based on the conclusion in this issue.
