### ISSUE TITLE
What are ontology representations for?

### ISSUE THREAD

**Issue by strogonoff** [ISO-TC211/www.isotc211.org#21]
I can see what UML models and XML schemas may be for, but am hazy on ontologies. A quick summary would help!

They seem to have different formats too, right? (some in RDF, some in XML)

**Comment by ronaldtse** [comment]
@strogonoff I am far from being conversant on ontologies, but this seems to be a good primer on it.
https://en.wikipedia.org/wiki/Ontology_(information_science) It's Tim-Berner Lee's version of the "new Internet".

**Comment by strogonoff** [comment]
Thanks, got it. I’ll keep it open for a bit longer to remind myself to understand it better.
