### ISSUE TITLE
Add Geolexica to TC 211 resource site navigation

### ISSUE THREAD

**Issue by strogonoff** [ISO-TC211/www.isotc211.org#22]
The site at www.isotc211.org contains some standard resources itself, and also serves as the index for standalone TC resource sites. In that role it should link to Geolexica (perhaps with lower priority than standard representation sites). Geolexica can be considered one of TC 211 resource sites, and it’s not easily discoverable currently.

**Comment by ronaldtse** [comment]
Thanks, I'd argue that Geolexica should be placed more prominently than others because the others (schemas, ontologies) aren't really for normal people to look at.

**Comment by strogonoff** [comment]
I assumed site audience does not include “normal people” as the majority, but point taken

**Comment by strogonoff** [comment]
If we want to include more mainstream audience I’ll definitely keep the ontology question open until there’s a good one-sentence description of what it is

**Comment by ronaldtse** [comment]
The Geolexica site can be used by people interested in or experts in the field of geographic information, while the other sites are used by people (and machines) that have already adopted ISO/TC 211 standards. So the former crowd is certainly larger than the latter 😉

**Comment by strogonoff** [comment]
Yes, larger in absolute terms, but not in terms of target audience for the site in its preexisting form. I see here that we might want to expand target audience for the site, noted.

**Comment by ronaldtse** [comment]
@strogonoff that's a good point -- thanks!

**Comment by ronaldtse** [comment]
@strogonoff I think we should add a section to the front page for TMG (Terminology Management Group, https://github.com/ISO-TC211/TMG/), the group that manages the MLGT (multi-lingual geographic terminology database) which is translated into https://www.geolexica.com . 

Right now we have 3 blocks:
<img width="782" alt="Screen Shot 2019-05-17 at 1 27 14 PM" src="https://user-images.githubusercontent.com/11865/57904978-7d62a880-78a7-11e9-963e-7936e85c666a.png">

**Comment by strogonoff** [comment]
This one is implemented, but layout testing under IE is still pending.

**Comment by strogonoff** [comment]
Confirmed that landing page layout under IE is OK
