### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#23]
```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-138578173-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-138578173-1');
</script>

````

**Comment by strogonoff** [comment]
@ronaldtse could you confirm that analytics is getting collected? GA script has been live for 12 hours or more.

**Comment by ronaldtse** [comment]
It's working! But do we need to add tracking codes for the other sites?

<img width="718" alt="Screen Shot 2019-05-22 at 9 06 02 AM" src="https://user-images.githubusercontent.com/11865/58140216-d6985680-7c70-11e9-9154-cfd3b8562679.png">
