### ISSUE TITLE
Move "Committee site" button to very apparent place on landing page

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#25]
From @MatsAhlin :
> ... could we at least on the landing page have link to the new committee page? I think you have had it before but now it does not to be there anymore.

Somehow during design optimization, the navigation bar where the committee site link got "hidden" and only accessible after opening the menu bar:

<img width="716" alt="Screen Shot 2019-05-15 at 6 49 10 PM" src="https://user-images.githubusercontent.com/11865/57771035-37410400-7744-11e9-82fd-b025ad4156a2.png">

This is to place the "Committee site" link to an apparent place without needing to click and open.

**Comment by strogonoff** [comment]
Fixed in 0.4.3. See new option https://github.com/ISO-TC211/jekyll-theme-isotc211/blob/master/_config.yml#L47 (off by default, turned on on www.isotc211.org only as of now).

**Comment by ronaldtse** [comment]
Confirmed working. Thanks @strogonoff !

**Comment by ronaldtse** [comment]
For the record, it looks like this now.

<img width="722" alt="Screen Shot 2019-05-16 at 12 08 03 PM" src="https://user-images.githubusercontent.com/11865/57825835-44f19a80-77d3-11e9-8071-910525dce060.png">

When shrunk:
<img width="654" alt="Screen Shot 2019-05-16 at 12 08 15 PM" src="https://user-images.githubusercontent.com/11865/57825841-49b64e80-77d3-11e9-8250-fddaf58c0cc0.png">
