### ISSUE TITLE
Provide address profiles from 19160-1 on resource site

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#26]
Address profiles are currently located at https://standards.iso.org/iso/19160/-1/

Since they are "resources", should we move them to the Resource site? @jetgeo @serenacoetzee @tedhabermann @ReesePlews 

Thanks!

**Comment by PeterParslow** [comment]
Remember, ISO 19160-1 contains the informative statement "Profiles may be published on the ISO website at http://standards.iso.org/iso/19160/-1/" (Annex B), with a short section (B.4) about how to achieve that (via the TC211 secretariat) - which repeats the path.

So whatever the "logical" answer, we would have to redirect people who got to the current path because it's in 'the standard'.

**Comment by ronaldtse** [comment]
Aha, in this case it’s settled. Let’s keep things there. Thanks @peterparslow !

**Comment by serenacoetzee** [comment]
I have not been following the discussion... but we could also do an
amendment of ISO 19160-1 to fix the path if that is what is necessary to
fix the problem...?

Serena Coetzee (GPr GISc 1245)

University of Pretoria
Director: Centre for Geoinformation Science
Professor and Head of Department Geography, Geoinformatics and Meteorology
Geography Building 1-3.7, Hatfield Campus, Lynnwood Road, Hatfield, 0083,
South Africa
email: serena.coetzee@up.ac.za · Web: www.up.ac.za/ggm · Mobile: +27 82 464
4294 · Tel: +27 12 420 3823

**Comment by PeterParslow** [comment]
I've never noticed much appetite for amending a standard: it requires the whole NWIP / project / risk of other clauses being commented on / full cycle of reviews - doesn't it?

**Comment by serenacoetzee** [comment]
It's a bit quicker, but yes, still a process...

Serena Coetzee (GPr GISc 1245)

University of Pretoria
Director: Centre for Geoinformation Science
Professor and Head of Department Geography, Geoinformatics and Meteorology
Geography Building 1-3.7, Hatfield Campus, Lynnwood Road, Hatfield, 0083,
South Africa
email: serena.coetzee@up.ac.za · Web: www.up.ac.za/ggm · Mobile: +27 82 464
4294 · Tel: +27 12 420 3823
