### ISSUE TITLE
Easy way to go to given ontology/scheme

### ISSUE THREAD

**Issue by strogonoff** [ISO-TC211/www.isotc211.org#4]
<img width="1146" alt="screen shot 2019-01-25 at 12 06 11 pm" src="https://user-images.githubusercontent.com/292959/51727062-cd212800-209c-11e9-8793-0dffd61b4fad.png">

Curious if the feature is likely to be of any use to human visitors, and will be worth enhancing (alternatively, wiping out?) after first version goes live.

Already functional in my branch/fork.

**Comment by ronaldtse** [comment]
@strogonoff I think this is useful but let's move it to the Schemas site (https://github.com/ISO-TC211/schemas.isotc211.org/)

**Comment by strogonoff** [comment]
@ronaldtse Sure. The reason for this widget on main TC site is to make schema discovery instructions slightly less user-unfriendly. If there’re no objections, I will move schema discovery instructions along with the widget to schemas.isotc211.org as the next step, and just link to the resource sites from the TC site.

**Comment by ronaldtse** [comment]
Thanks @strogonoff -- the main site already has a link to the schemas site, so maybe just update the description a bit if necessary 👍

**Comment by strogonoff** [comment]
Sure. The original TC site version not only linked to schemas but also tried to describe the URL pattern for finding schemas etc., which seemed a bit unwelcoming to the visitor, hence the widget on TC site.

**Comment by strogonoff** [comment]
Agreed on both counts, will update  resource sites after main TC site itself is switched to the theme (which is delayed due to my decision to fit some Metanorma landing work after Geolexica, but should be done this week). Then will reorganize the content across main & resource sites a bit. Planning to clean up the main site and possibly borrow some ideas from TC pages on ISO.org.

**Comment by ronaldtse** [comment]
@strogonoff this is all done, right? If so please help close it. Thanks!

**Comment by strogonoff** [comment]
This is to be migrated to respective schema and XML sites right now

**Comment by strogonoff** [comment]
These were ported to ontology and schema resource sites.
