### ISSUE TITLE
add anchors to MG headings on the main page

### ISSUE THREAD

**Issue by ReesePlews** [ISO-TC211/www.isotc211.org#41]
presently it is i not possible to make a link to a single MG heading on the main page. can an anchor be added to each of the headings?

instead of just  using this link   https://www.isotc211.org/  i would like to have  https://www.isotc211.org/#Terminology

**Comment by ronaldtse** [comment]
Thanks for the suggestion @ReesePlews , the following HTML `id`s have been added now.
You can now refer to each MG section as:

* e.g. https://www.isotc211.org/#resource-terminology

```
resource-isogr
resource-standards
resource-models
resource-schemas
resource-terminology
resource-ontologies
resource-registry
```
