### ISSUE TITLE
MLGT Feedback link on main TC211 Resource page is broken

### ISSUE THREAD

**Issue by ReesePlews** [ISO-TC211/www.isotc211.org#42]
on the main TC211 resources page

the link under Terminology for MLGT feedback seems to be broken

Feedback: [Online MLGT feedback page](https://isotc211.geolexica.com/feedback)

i actually do not recall where the feedback was to be recorded?  was it a google sheet or somewhere in github?

**Comment by ReesePlews** [comment]
if this is difficult to fix because it may have not been decided where the feedback was going to be recorded, could a simple form with a captcha be added that just sent the form contents to an email address (TMG convenor address) ? no archiving or keeping of the feedback would be maintained at this time. if possible it would be good to have this fixed before the 2022-05 TMG meeting. thank you

**Comment by ronaldtse** [comment]
Thank you @ReesePlews ! Sorry this was a mistake on our part during migration from the .com to the .org address. Will get it fixed.

**Comment by ronaldtse** [comment]
@ReesePlews this is fixed, can you please help verify? Thanks!

**Comment by ReesePlews** [comment]
@ronaldtse Thank you for fixing the form. i confirm it works and a copy of a test was received from the submitted email address. i think everything is working ok now. thank you,
