### ISSUE TITLE
URL availability under `/2005/` (ISO 19139, 19110, 19139-2, 19145)

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#5]
Courtesy of Mats:

http://www.isotc211.org/2005/gco                                                                         
http://www.isotc211.org/2005/gmd                                                                       
http://www.isotc211.org/2005/gmx                                                                       
http://www.isotc211.org/2005/gss                                                                          
http://www.isotc211.org/2005/gsr                                                                          
http://www.isotc211.org/2005/gts

The contents of these URLs are available, e.g. https://www.isotc211.org/2005/gmd/gmd.xsd

But if you go to let say the URL http://www.isotc211.org/2005/gts , a 404 is shown because there's no `index.html`. 

What are we supposed to do here?

ping @tedhabermann @jetgeo

**Comment by ronaldtse** [comment]
> ISO 19110 has the link: http://www.isotc211.org/2005/gfc
> It feels related to the 19139 mentioned above, so whatever we say we do with them would be for this one as well.

> ISO 19139-2 has the link: http://www.isotc211.org/2005/gmi
> It feels related to the 19110 & 19139 mentioned above, so whatever we say we do with them would be for this one as well.
 
> ISO 19145 has the link: http://www.isotc211.org/2005/gplr
> It feels related to the 19110, 19139 & 19139-2 mentioned above, so whatever we say we do with them would be for this one as well.

**Comment by PeterParslow** [comment]
Do remember the distinction between URIs used as namespace identifiers & those used as e.g. XML schemaLocations

The three you have above are namespace identifiers, which don't need to be de-referenceable, although it's friendly practice.

Schema locations - and especially xsd:import / xsd:include from our own schemas! - do need to 'work'.

So, in 19115-3 for example, Ted went to great lenghts to populate the XSD directory with really helpful index.html files.

The namespace http://standards.iso.org/iso/19115/-3/md1/1.0 is defined in the file at https://standards.iso.org/iso/19115/-3/md1/1.0/md1.xsd, and by doing that, the namespace itself can be dereferenced, and if you then open the index.html, you get a really helpful guide to what's going on in that particular little bit of the standard.

That's the modern handling of the replacement for http://www.isotc211.org/2005/gmd (if I get my 'bits of 19115' correct).

**Comment by ronaldtse** [comment]
@PeterParslow indeed the question is about friendly practice.

The equivalent of the http://standards.iso.org/iso/19115/-3/md1/1.0 index page is available at https://schemas.isotc211.org/19115/-3/md1/1.0 . 

The question is whether we want the index pages for the `/2005/` ones, and if so, how do we get them done.

**Comment by ronaldtse** [comment]
I've made index files for all of the links under `/2005/` so that the uninformed reader can render these links, e.g.

* http://www.isotc211.org/2005/gco
* http://www.isotc211.org/2005/gmd
* http://www.isotc211.org/2005/gmx
* http://www.isotc211.org/2005/gss
* http://www.isotc211.org/2005/gsr
* http://www.isotc211.org/2005/gts

**Comment by ronaldtse** [comment]
Done in ad1a92f5cba99b9e3fc69f3c6db6b689eae8631e
