### ISSUE TITLE
ISO 19112 links

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#8]
From Mats:

> ISO 19112 has the following links:
http://standards.isotc211.org/19112/-1/2/conf/srs
http://standards.isotc211.org/19112/-1/2/req/srs
http://standards.isotc211.org/19112/-1/2/conf/gaz
http://standards.isotc211.org/19112/-1/2/req/gaz
http://standards.isotc211.org/19112/-1/2/req/srs/srs
http://standards.isotc211.org/19112/-1/2/req/gaz/sch
http://standards.isotc211.org/19112/-1/2/req/gaz/mng
http://standards.isotc211.org/19112/-1/2/conf/srs/srs
http://standards.isotc211.org/19112/-1/2/conf/gaz/sch
http://standards.isotc211.org/19112/-1/2/conf/gaz/mng

> I will confer with Rob on these.  Since 19112 is about to be release this or next week. I am not sure if he were aiming for standards.iso.org but even then it would be in error from how those links are created.

The thing is we only have {www,def,schemas}.isotc211.org but not "standards.isotc211.org". 

What do we do here?

ping @jetgeo @tedhabermann

**Comment by ronaldtse** [comment]
@jetgeo @tedhabermann what's the best course of action here?

**Comment by jetgeo** [comment]
We need to create these links. "standards.isotc211.org" is the main structure we will use for normative statements, conformance classes and conformance tests.

**Comment by ronaldtse** [comment]
Will “standards” point to “def”, “www” or “schemas”? Or is that a separate site?

**Comment by jetgeo** [comment]
Separate site :).

**Comment by ronaldtse** [comment]
Separate host name (which can be done by redirect) or separate site (different content)? :wink:

**Comment by jetgeo** [comment]
Uhh... not sure. I suppose separate host name. The URLs must be resolvable, and we must be able to put content there, e.g. some kind of structured description of the statements, conformance class or test. Does that help you decide?

**Comment by ronaldtse** [comment]
Does this mean that content of "standards.isotc211.org" will differ from that of "def" "www" and "schemas"?

Given our current setup it won't really cost more but the more sites the more headaches 😉

**Comment by jetgeo** [comment]
Yes, the content is different. 
- def.isotc211.org is for the ontologies
- schemas.isotc211.org is for XML schemas
- standards.isotc211.org is for normative statements and conformance
- www.isotc211.org is the main address for resources. 

Did I understand your question?

**Comment by ronaldtse** [comment]
Thank you, it's the perfect answer.

So we will create the new site. Do we already have existing data to migrate to standards.isotc211.org?

**Comment by jetgeo** [comment]
I don't think we have any content yet, but the links at the top of this discussion should be resolvable, i.e. we need to have the subfolders that describe the structure.

**Comment by ronaldtse** [comment]
@jetgeo the site is up! We’ll deal with the exact content updating mechanisms later, but please help review it.  Closing this for now. 

https://standards.isotc211.org

**Comment by jetgeo** [comment]
Looks good for now, except that I think the example links should be resolvable. I get a 404 when I click in them.

**Comment by ronaldtse** [comment]
@jetgeo those links are not resolvable because the content is not ready? Is the content ready now?

**Comment by ronaldtse** [comment]
Already setup new issue for willing in ISO 19112 links.
